# Generated by Django 3.2 on 2023-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='recipe_for_tags', to='recipes.Tag', verbose_name='Tags'),
        ),
    ]
