# Generated by Django 3.2 on 2023-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipe_ingredients', through='recipes.IngredientsInRecipe', to='recipes.Ingredient', verbose_name='Ingredients'),
        ),
    ]
