# Generated by Django 3.2 on 2023-02-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipe',
            options={'default_related_name': 'Ingr_in_res', 'verbose_name': 'Ingredients in recipe'},
        ),
    ]
