# Generated by Django 3.2 on 2023-03-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230302_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
