# Generated by Django 3.2 on 2023-03-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredientsinrecipe_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsinrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
